/* HYDRO FARM — STAGE 2: HiveMQ Cloud + GH001 */
const CONFIG={greenhouse:"GH001",telemetry:"greenhouse/GH001/telemetry",controlBase:"greenhouse/GH001/control",actuatorState:"greenhouse/GH001/actuators/+/state",status:"greenhouse/GH001/status",alerts:"greenhouse/GH001/alerts"};
let client=null,controlMode="AUTO";
const state={pump:false,fan:false,pad_cooling:false};
const $=id=>document.getElementById(id);
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(window._t);window._t=setTimeout(()=>e.classList.remove("show"),2200)}
function mqttStatus(ok,text){$("mqttState").textContent=ok?"MQTT متصل":(text||"MQTT غير متصل");$("mqttSub").textContent=ok?"HiveMQ Cloud • GH001 • Online":"HiveMQ Cloud • GH001 • Offline";$("connectionDot").className="dot "+(ok?"online":"offline")}
function val(id,v,u=""){if(v!==undefined&&v!==null)$(id).textContent=String(v)+u}
function bool(v){if(typeof v==="boolean")return v;if(typeof v==="number")return v!==0;return["1","true","on","ON","yes"].includes(String(v))}
function mode(m){controlMode=String(m).toUpperCase()==="MANUAL"?"MANUAL":"AUTO";$("mode").textContent=controlMode;$("homeMode").textContent=controlMode;["pump","fan","pad"].forEach(x=>{const e=$(x+"Mode");if(e)e.textContent=controlMode});$("padMode").textContent=controlMode}
function actuator(d,on,send){state[d]=on;const id=d==="pad_cooling"?"padSwitch":d+"Switch";$(id)?.classList.toggle("on",on);if(send)publish(d,on)}
function publish(d,on){if(!client?.connected){toast("MQTT غير متصل");return}const topic=`${CONFIG.controlBase}/${d}/set`;const payload=JSON.stringify({greenhouse:"GH001",device:d,state:!!on,mode:controlMode,timestamp:Date.now()});client.publish(topic,payload,{qos:1},e=>toast(e?"فشل إرسال الأمر":`${d} → ${on?"ON":"OFF"}`))}
function telemetry(d){const t=d.airTemperature??d.temperature??d.temp,h=d.airHumidity??d.humidity??d.hum,w=d.waterTemperature??d.waterTemp,l=d.waterLevelPercent??d.levelPercent??d.level;val("temp",Number.isFinite(+t)?(+t).toFixed(1):t," °C");val("hum",Number.isFinite(+h)?(+h).toFixed(1):h," %");val("wt",Number.isFinite(+w)?(+w).toFixed(1):w," °C");val("level",Number.isFinite(+l)?(+l).toFixed(0):l," %");val("ec",d.ec??d.EC);val("ph",d.ph??d.pH);if(d.mode)mode(d.mode);["pump","fan","pad_cooling"].forEach(x=>{if(d[x]!==undefined)actuator(x,bool(d[x]),false)});if(d.actuators)Object.keys(d.actuators).forEach(x=>{if(state[x]!==undefined)actuator(x,bool(d.actuators[x]),false)})}
function connect(){if(typeof mqtt==="undefined"){toast("مكتبة MQTT غير موجودة");return}if(client)try{client.end(true)}catch(e){}const host=$("mqttHost").value.trim(),port=+$("mqttPort").value,user=$("mqttUser").value.trim(),pass=$("mqttPass").value;if(!host||!port||!user||!pass){toast("أدخل بيانات HiveMQ كاملة");return}mqttStatus(false,"جاري الاتصال...");client=mqtt.connect(`wss://${host}:${port}/mqtt`,{username:user,password:pass,clientId:"hydro-gh001-"+Math.random().toString(16).slice(2),clean:true,connectTimeout:10000,reconnectPeriod:3000,keepalive:30});client.on("connect",()=>{mqttStatus(true);toast("تم الاتصال بـ HiveMQ");client.subscribe([CONFIG.telemetry,CONFIG.actuatorState,CONFIG.status,CONFIG.alerts],{qos:1})});client.on("reconnect",()=>mqttStatus(false,"إعادة الاتصال..."));client.on("offline",()=>mqttStatus(false,"Offline"));client.on("close",()=>mqttStatus(false,"الاتصال مغلق"));client.on("error",e=>{console.error(e);mqttStatus(false,"خطأ MQTT")});client.on("message",(topic,b)=>{let d;try{d=JSON.parse(b.toString())}catch{d={message:b.toString()}}if(topic===CONFIG.telemetry)return telemetry(d);if(topic.startsWith("greenhouse/GH001/actuators/")&&topic.endsWith("/state")){const x=topic.split("/")[3];if(state[x]!==undefined)actuator(x,bool(d.state??d.on??d.value??d),false)}if(topic===CONFIG.status)console.log("GH001 status",d);if(topic===CONFIG.alerts)toast(d.body||d.message||"تنبيه من GH001")})}
$("mqttConnect").onclick=connect;
document.querySelectorAll(".sw").forEach(e=>e.onclick=()=>{if(controlMode!=="MANUAL"){toast("غيّر الوضع إلى MANUAL أولاً");return}actuator(e.dataset.device,!state[e.dataset.device],true)});
$("mode").onclick=()=>{const m=controlMode==="AUTO"?"MANUAL":"AUTO";mode(m);if(client?.connected)client.publish(`${CONFIG.controlBase}/mode/set`,JSON.stringify({greenhouse:"GH001",mode:m}),{qos:1});toast("الوضع: "+m)};